# Quality Gate Config for Vue / React / Frontend
version: 1

secret:
  enabled: true

syntax:
  enabled: true

security:
  enabled: true

format:
  enabled: true
  auto_fix: true

lint:
  enabled: false

architecture:
  enabled: false
